name: Java CI with Maven and Auto-Merge

on:
  push:
    branches: ["master", "tijani"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Maven tests
        run: mvn clean verify

      - name: Auto-merge tijani into dev if tests pass
        if: github.ref == 'refs/heads/tijani' && success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git fetch origin dev
          git checkout dev
          git merge origin/tijani --no-edit

          git push origin dev
