name: Java CI with Maven and Auto-Merge

on:
  push:
    branches: ["master", "tijani"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git merge

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Wait for MongoDB to be ready
        run: |
          until mongosh --eval 'db.runCommand({ ping: 1 })' --quiet; do
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Run Maven tests
        run: mvn clean verify

      - name: Auto-merge tijani into dev if tests pass
        if: github.ref == 'refs/heads/tijani' && success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git fetch origin dev
          git checkout dev
          git merge origin/tijani --no-edit

          git push origin dev
