name: Java CI with Maven and Auto-Merge

on:
  push:
    branches: ["master", "tijani"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="echo 'db.runCommand({ ping: 1 })' | mongosh localhost/test --quiet"
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install netcat (for waiting on MongoDB)
        run: sudo apt-get update && sudo apt-get install -y netcat

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready on port 27017..."
          for i in {1..15}; do
            nc -z localhost 27017 && echo "✅ MongoDB is ready." && exit 0
            echo "Still waiting..."
            sleep 2
          done
          echo "❌ MongoDB did not become ready in time."
          exit 1

      - name: Run Maven tests
        working-directory: 3kstBackend
        run: mvn clean verify

      - name: Auto-merge tijani into dev if tests pass
        if: github.ref == 'refs/heads/tijani' && success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout -b dev origin/dev || git checkout dev
          git merge origin/tijani --no-edit
          git push origin dev
